# Generated by Django 5.1.2 on 2024-10-28 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_moto', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='products_category')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='products_images')),
                ('price', models.IntegerField()),
                ('details', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_fee', models.IntegerField(default=290)),
                ('down_payment_3_months', models.FloatField(default=30.0)),
                ('down_payment_6_months', models.FloatField(default=20.0)),
                ('down_payment_9_months', models.FloatField(default=15.0)),
                ('down_payment_12_months', models.FloatField(default=10.0)),
                ('fee_3_months', models.FloatField(default=10.0)),
                ('fee_6_months', models.FloatField(default=15.0)),
                ('fee_9_months', models.FloatField(default=20.0)),
                ('fee_12_months', models.FloatField(default=30.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
